/**********************************************************************************

Copyright (C) 2005-2016 Intel Corporation.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
- Neither the name of Intel Corporation nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY INTEL CORPORATION "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL INTEL CORPORATION BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**********************************************************************************/

#include <string.h>

#include "mfx_vaapi_debug.h"

#undef MFX_DEBUG_MODULE_NAME
#define MFX_DEBUG_MODULE_NAME "mfxvaapidebug"

#if MFX_DEBUG == MFX_DEBUG_YES

MFX_DEBUG_DEFINE_VALUE_DESC_PRINTF(
  VAStatus,
  MFX_DEBUG_VALUE_DESC(VA_STATUS_SUCCESS),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_OPERATION_FAILED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ALLOCATION_FAILED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_DISPLAY),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_CONFIG),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_CONTEXT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_SURFACE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_BUFFER),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_IMAGE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_SUBPICTURE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ATTR_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_MAX_NUM_EXCEEDED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_PROFILE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_RT_FORMAT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_BUFFERTYPE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_SURFACE_BUSY),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_FLAG_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_PARAMETER),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_RESOLUTION_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNIMPLEMENTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_SURFACE_IN_DISPLAYING),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_IMAGE_FORMAT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_DECODING_ERROR),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ENCODING_ERROR))

#endif // #if MFX_DEBUG == MFX_DEBUG_YES
